### ISSUE TITLE
mDNS resolve?

### ISSUE THREAD

**Issue by slowpoison4** [levkovigor/MQTT_VPN_ESP32#1]
Hi!

This works perfectly with the ESP32! Thanks for the fork.
I had a question/doubt: 
I have 100 devices of ESP32 scattered around the city collecting data of Air quality. They are all connected to different networks. While they do post the data to my web server on the cloud, each of these devices have a web server running on them with mDNS corresponding to their device ID(Similar to the example). If i use the above code, can i access them using their unique device ID? for eg: I would like to access them via <deviceID>.local:81 instead of 10.0.1.2 since this has to manually be added to every device.   any advice would be highly appreciated. I tried access the example webserver via mDNS but it doesnt seem to resolve it.

**Comment by levkovigor** [comment]
I didn't check, but I think mDNS will not work in this solution. You can use different addresses 10.0.1.2 - 10.0.1.255.

But I recommend not to use webserver on ESP with ip_over_mqtt for your project. It's better to make web app on server with sql database for collecting data from all ESP devices. You can get and send data from esp to server with simple POST and GET requests and use simple mqtt commands from web app to any ESP device for fast reaction on remote device. With this functionality you also can make remote firmware update on ESP. It will be better solution.

**Comment by levkovigor** [comment]
> 
> 
> Hi!
> 
> This works perfectly with the ESP32! Thanks for the fork.
> I had a question/doubt:
> I have 100 devices of ESP32 scattered around the city collecting data of Air quality. They are all connected to different networks. While they do post the data to my web server on the cloud, each of these devices have a web server running on them with mDNS corresponding to their device ID(Similar to the example). If i use the above code, can i access them using their unique device ID? for eg: I would like to access them via .local:81 instead of 10.0.1.2 since this has to manually be added to every device. any advice would be highly appreciated. I tried access the example webserver via mDNS but it doesnt seem to resolve it.

I didn't check, but I think mDNS will not work in this case. You can use different ip address for each device 10.0.1.2 - 10.0.1.255

But it is not the better solution to use web server on esp. I recommend to make web app on your server with sql database for collecting all received data. ESP devices can make GET and POST HTTP requests for getting or sending data to server. And you can add simple MQTT commands via MQTT Broker on server to make fast communication from web app to any ESP device. Also it is easy to make remote firmware update with this functionality. So it will be better choice for your project.
