### ISSUE TITLE
mqtt_vpn.c on the cloud

### ISSUE THREAD

**Issue by garudaonekh** [levkovigor/MQTT_VPN_ESP32#2]
hi, instead of running mqtt_vpn.c on Linux machine and directly access that machine, can I run it on cloud instead and access that cloud from another machine thru the cloud public ip? My scenario is to access from mobile phone

I mean I want to run mqtt_vpn on a Linux cloud and access it from phone via the public ip of that Linux.

Here's the flow that I want:
Phone <---http--> Linux cloud(mqtt_vpn, mqtt broker)<---MqTT-->ESP32

**Comment by levkovigor** [comment]
> 
> 
> hi, instead of running mqtt_vpn.c on Linux machine and directly access that machine, can I run it on cloud instead and access that cloud from another machine thru the cloud public ip? My scenario is to access from mobile phone
> 
> I mean I want to run mqtt_vpn on a Linux cloud and access it from phone via the public ip of that Linux.
> 
> Here's the flow that I want: Phone <---http--> Linux cloud(mqtt_vpn, mqtt broker)<---MqTT-->ESP32

Of course you can. But I recommend to make simple mqtt protocol to communicate directly between phone and esp32 through cloud mqtt broker without vpn over mqtt

**Comment by garudaonekh** [comment]
yes, i got your point. the reason i need VPN because I want user to be able to locally manage the device and the second reason is we already have a UI on the device so donot want to recode it on server again.

**Comment by garudaonekh** [comment]
Anyhow, i got your code working by installing it on Digitalocean and access it from phone via Apache proxy.

**Comment by garudaonekh** [comment]
However, we have a problem with ws(websocket). it keep closing the connection after 1 or 2 seconds. Do you have any idea why?
I use your code with ESPUI library for esp32

**Comment by levkovigor** [comment]
@garudaonekh 

Better to ask @martin-ger (https://github.com/martin-ger/MQTT_VPN ) who developed the main code. I just adapted it for Arduino IDE.  
That's why I proposed to use simple mqtt protocol. You can easy move esp32 UI to external apache server with mqtt broker and make mqtt communication between phone and esp32 through server web interface with simple mqtt commands by device ID. It will work better, more stable and reliably.

**Comment by garudaonekh** [comment]
thanks
