### ISSUE TITLE
pbuf_free exception

### ISSUE THREAD

**Issue by garudaonekh** [levkovigor/MQTT_VPN_ESP32#3]
pbuf_free exception after a few MQTT request/response

This error happen after a few MQTT request/response. However, if I remove MQTT the code program work fine.

"ERROR Message"
assertion "pbuf_free: p->ref > 0" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/pbuf.c", line 766, function: pbuf_free
abort() was called at PC 0x4010df83 on core 0

The error decoder point it to: 0x400da8e1: packet_receive_handler at /Users/***/-Firmware-master/mqttif.c:350

**Comment by levkovigor** [comment]
@garudaonekh Did you add something to default code?

**Comment by garudaonekh** [comment]
I don't edit your existing library code.

Here's the code I used:

```
wifi_server->begin();
P4_ADDR(&ipaddr, 10,0,1,2);
IP4_ADDR(&netmask, 255,255,255,255);
IP4_ADDR(&gw, 0,0,0,0);
mqtt_vpn_if_init(broker, mqtt_user, mqtt_password, "mqttip", vpn_password, ipaddr, netmask, gw);

```

**Comment by garudaonekh** [comment]
It's this line in the code that cause the crash: 
```
static void packet_receive_handler(void* handler_args, esp_event_base_t base, int32_t id, void* event_data)
{ ...
if (mqtt_if->netif.input(pb, &mqtt_if->netif) != ERR_OK)
...
```

The hard part for me is that it happen randomly after several MQTT message received.

**Comment by levkovigor** [comment]
@garudaonekh 

Better to ask @martin-ger (https://github.com/martin-ger/MQTT_VPN ) who developed the main code. I just adapted it for Arduino IDE.
