### ISSUE TITLE
Auto reconnect to MQTT Broker

### ISSUE THREAD

**Issue by garudaonekh** [levkovigor/MQTT_VPN_ESP32#4]
Hi,
The device code auto connect but the server mqtt_vpn.c doesn't

I see that the server library doesn't auto reconnect to the broker when the connection is lost. I don't know how to do this with this library as I am not familiar with the mqtt library used here. I have experience with Python MQTT client, it has auto reconnect and auto resubscribe feature.

Thanks;

**Comment by levkovigor** [comment]
@garudaonekh 

Better to ask @martin-ger (https://github.com/martin-ger/MQTT_VPN ) who developed the main code. I just adapted it for Arduino IDE.

**Comment by garudaonekh** [comment]
thanks
